enable prompt and dscover apis for PebbloSafeRetriever.
daxa-ai/langchain pull request #31
Opened 2024-04-19 17:05 UTC by rahul-trip

This PR includes code changes for:

- /app/discover and /prompt apis for  PebbloSafeRetriever apps.
- accept api_key for Pebblo-cloud 

Excludes:

- linting and formatting
- beautification.

2024-04-25 05:35 UTC, shreyas-damle commented on libs/langchain/langchain/chains/pebblo_retrieval/base.py
> +            "user": auth_context.username if auth_context else "unknown",
Do we want to capture it as `unknown` or just keep empty?

2024-04-25 05:35 UTC, shreyas-damle commented
Added one minor comment, rest LGTM.

2024-04-30 05:37 UTC, Raj725 requested changes

2024-04-30 05:37 UTC, Raj725 commented on libs/langchain/langchain/chains/pebblo_retrieval/models.py
> +    vector_dbs: List[VectorDB] | None
This is throwing error in python 3.9

2024-04-30 05:37 UTC, Raj725 commented on libs/langchain/langchain/chains/pebblo_retrieval/base.py
> +                        "embedding_model": kwargs['retriever'].vectorstore._embeddings.model
Attribute `_embeddings` is not available on all the vectorstores, it's failing for Pinecone

2024-07-09 12:51 UTC, closed without merging